name: ".NET Release"

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --filter "Category!=Integration" --no-build --verbosity normal
      - name: Publish win-x64
        run: dotnet publish src/YoloKonsole/YoloKonsole.csproj  \
          -r win-x64 \
          -p:PublishSingleFile=true \
          -o releases/win-x64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: YoloKonsole ${{ github.ref }}
          body: |
            ## HOWTO (win-x64):

            - download `YoloKonsole.exe` and `appsettings.json` and save to a new folder on your computer
            - ensure you have [.NET 9.0 runtime](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-9.0.0-windows-x64-installer) installed
            - run `./setup-secrets.ps1` to set up your secrets (you can edit the script to change the secrets path)
            - run `./run-yolo.ps1` from the command line is best so that you can see the output easily (`Windows`+`R`, `cmd`)
          draft: true
          prerelease: false
      - uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "releases/**/*.exe;releases/**/*.json;releases/**/*.ps1;releases/**/*.md"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
